[project]
name = "hello-openai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv-python>=0.0.1",
    "httptools>=0.6.4",
    "openai>=1.52.2",
    "uvicorn>=0.32.0",
]
