[project]
name = "hello-python3-12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httptools>=0.6.4",
    "uvicorn>=0.30.6",
    "uvloop>=0.19.0",
]
