[project]
name = "hello-pypy-10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httptools>=0.6.4",
    "uvicorn>=0.30.1",
    "uvloop>=0.21.0",
]
